[MERCHATS-14] Endpoints para cadastrar permissão e conceder permissão para identidade
geru-br/keyloop pull request #20
Opened 2020-03-13 18:55 UTC by guilhermegeru

**Story:** [MERCHANTS-10](https://geruteam.atlassian.net/browse/MERCHANTS-10)
**Subtask:** [MERCHANTS-14](https://geruteam.atlassian.net/browse/MERCHANTS-14)

**Changes:**
-
- Add endpoint POST `/realms/{realm_slug}/identities/{id}/permissions` to register a permission;
- Add endpoint POST `/realms/{realm_slug}/identities/{id}/permissions/{perm_grant_id}` to grant permission to some identity. In case of success, returns the same schema of permission creation;
- Implement both endpoints in `playground`.

2020-03-13 21:03 UTC, doubleG-geru approved these changes
![](https://media.giphy.com/media/ckeHl52mNtoq87veET/giphy.gif)

2020-03-13 21:35 UTC, ffardogeru reviewed
Parece bom. Deixei alguns comentários em pontos que me chamaram a atenção

2020-03-13 21:35 UTC, ffardogeru commented on keyloop/api/v1/permission_grant.py
> +    200: PermissionSchema,
Vale verificar se é instância ou classe

2020-03-13 21:35 UTC, ffardogeru commented on keyloop/ext/sqla/identity.py
> +        if 'username' in kwargs.keys():
Podemos usar com sem o .keys()
```suggestion
        if 'username' in kwargs:
```

2020-03-13 21:35 UTC, ffardogeru commented on keyloop/ext/sqla/identity.py
> +        elif 'uuid' in kwargs.keys():
Idem

2020-03-13 21:35 UTC, ffardogeru commented on keyloop/ext/sqla/identity.py
> +        if 'username' in kwargs.keys():
Sugestão, executar a query num único try except e compor o filtro em função do parâmetro

2020-03-16 13:58 UTC, merged

2020-03-16 15:39 UTC, jsbueno-geru requested changes
Então  -o merge já foi - talvez em vez de "ressucitar" a Merchants-14, como pedi bastante mudança,e algumas são mais estruturais, valha a pena abrir uma outra subtask para essas mudanças.

2020-03-16 15:39 UTC, jsbueno-geru commented on keyloop/api/v1/exceptions.py
> +
Acho que vale a pena dar uma melhorada nessa hierarquia aí - 

eu me imagino escrevendo um trecho de código em que se deu um erro na permissão, não tem diferença
de que erro foi, e vou ter que fazer a mesma coisa (passar a mensagem para o usuário, por exemplo, 
ou simplesmente negar algo) 

Então acho que `Exception->KeyloopError->PermissionError->(PermissionNotFound, PermissionAlreadyExist, PermissionAlreadyGranted)` - o nível de "KeyloopError" poderia ser adicionado as que exceções que já existem no arquivo: mal não vai fazer, e pode ajudar com logging/debuging lá na frente.

2020-03-16 15:39 UTC, jsbueno-geru commented on keyloop/api/v1/identity.py
aqui, mais só pra eu entender - tem alguma diferença?

2020-03-16 15:39 UTC, jsbueno-geru commented on keyloop/api/v1/permission.py
> +            )
O resource inteiro com 15 linhas! :-)

Achoq ue aqui é que vemos que valeu a pena a briga toda até agora!  Ficou legal.

2020-03-16 15:39 UTC, jsbueno-geru commented on keyloop/api/v1/permission_grant.py
> +            return
Será que faz sentido retornar um erro nesse caso?
poderia ser uma mensagem de ok com mensagens dizendo que nada foi alterado.

Logar essas coisas também é importante (não tem nenhum logging acima também, né?) 

Em particular, só eu não consigo perceber como retornar um erro se algo "já está feito" pode melhorar qualquer coisa pra quem usa o serviço. 

(A mensagem "HTTP 304 not modified"  poderia parecer ok, se olharmos só o inglês, mas a ideia do código é que seja usado nos mecanismos de cache - então acho que tem que voltar um 200 mesmo, e achar algum ponto no corpo da resposta pra dizer que a chamada foi redundante)

2020-03-16 15:39 UTC, jsbueno-geru commented on keyloop/ext/sqla/identity.py
> +    def get_by(self, **kwargs):
# importante

**não pode mudar aqui** de "get" para "get_by" **sem mudar a interface do IdentitySource**  - quer dizer, até pode por um método a mais aqui - mas esta classe tem que continuar atendendo a interface, e principalmente, o código que _usa_ essa classe pra buscar identitys só pode chamar os métodos declarados na interface. 

E ao mudar a interface, tem que ter em mente que é uma mudança obrigatória para **todos os usuários da biblioteca**. Nesse ponto do projeto isso ainda é viável - 
mas mais pra frente não vai mais ser. Então, tem que considerar com calma, se faz sentido só o  `get_by` em vez do `get` ou se fazem sentido os dois - e adequar a interface (e todas as implementações) para satisfazerem isso.  


Numa segunda leitura - acho que dá pra manter o método `get` mesmo, aceitando os dois parâmetros - e muda-se os parâmetro na interface. Não é por que o método do sqlaclhemy chama  `get_by` que o nosso precisa chamar  `get_by`.  o Sqlalchemyy precisou dos dois justamente por conta da assinatura distinta - se em todos os nossos métodos formos aceitar alguns parametros distintos para o `get`, não precisa ser `get_by`.

2020-03-16 15:39 UTC, jsbueno-geru commented on keyloop/ext/sqla/identity.py
> +                raise IdentityNotFound
Não faz sentido usar `kwargs` na assinatura do método, e depois pegar dois parâmetros específicos do `kwargs` .

Da mesma forma, o código todo da query é o mesmo, só muda o campo - talvez valha mais a pena algo do tipo:


```python

@singletonmethod
def get_by(self, id = None, username = None):
    if int(bool(id)) + int(bool(username)) != 1:  # (não gostei muito disso na verdade - se pensar em algo suscinto e legível para testar se apenas um dos parâmetros foi passado, pode trocar)
        raise NoResultFound("Only one of 'id' or 'username' must be passed")
    filter_field = self.model.username if username else self.model.id
    search_arg = username if username else id
    try:
        return (self.session
                .query(self.model)
                .filter(filter_field == search_arg, self.model.active == True)
                .one())
    except NoResultFound:
        raise IdentityNotFound()  # a convenção é dar raise sempre em instâncias de Exceptions - apesar de funcionar com classes.

```

2020-03-16 15:39 UTC, jsbueno-geru commented on keyloop/ext/sqla/permission.py
> +
Talvez `get` seja um nome melhor - como descrevi acima.

Também seria legal normalizar o código oara ter um bloco só, e sem kwargs para parâmetros já conhecidos e fixos. (como no outro exemplo que comentei)

2020-03-16 15:39 UTC, jsbueno-geru commented on keyloop/interfaces/permission.py
> +        pass
como acima-  talvez mudar pra `get`?

2020-03-16 15:39 UTC, jsbueno-geru commented on keyloop/schemas/permission.py
> +    description = fields.String(required=True, validate=lambda x: True if x != "" else False)  # Empty string not accepted
Será que a description é algo tão importante assim, pra não aceitarmos uma description vazia?
As permissions "permssions' (não "principals") no Pyramid são coisas tão simples como 'view', 'edit', 'delete' - as vezes não tem muito mais o que colocar numa description - isso pode se tornar uma armadilha de só ter que ficar replicando a string da permission no description. Talvez ela não  precise ser required.

2020-03-16 15:39 UTC, jsbueno-geru commented on playground/models.py
> +
espera - eu não tava entendo bem o conceito de "permission grant" e só entendi aqui - é a "instância de uma permissão para um identity" . Legal - fui ver por que não tinha entendido - é por que no Schema de PermissionGrant não aparece  Identity.

( A interface está certa. Mas temos que pensar que no momento, a interface tem que refletir o Schema mais por conta de não termos uma ferramenta que gere a interface sozinha a partir do Schema )


Temos que ter em mente que  e o Schema, no contexto do Keyloop, é o nosso "model" . Lá é que tem que aparecer todos os campos e tudo que for relacionado a uma identidade - se para um deerminado endpoint não precisamos de alguns dos campos, ou precisamos de campos a mais, tem que usar as lista `include`  e `exclude`

Então se todos os endpoints de permission tem uma identity implícita, e acessam o permission por nome, não por ID, isso tem que se rrefletido nso endpoints  - mas o Schema tem que ser algo que eu bata o olho e entenda que esse objeto faz o relacionamento de uma Permission pra um Idenitity - essa informação não tem que ficar nas implementações de referência (ext.sqla)  e menos ainda no playground.

2020-03-16 15:39 UTC, jsbueno-geru commented on keyloop/schemas/permission.py
> +    perm_name = fields.String(required=True)
**importante** - isso aqui não representa a ideia de um "permison_grant" - veja o que comentei na declaração da table no playground.

2020-03-16 15:39 UTC, jsbueno-geru commented on keyloop/ext/sqla/permission.py
> +        return permission
Precisa ter algo do PermissionGranted no ext.sqla -  
mesmo que os métodos tenham que ser re-escritos, por conta de ser necessário referências a tabelas concretas lá no
playground.


Talvez seja o caso de ter uma classe PermissionGrant aqui, mesmo que ela seja vazia, pra conter a tabela "fisica" que é declarada depois - mas não dá pra deixar quem optar por usar o keyloop "adivinhar" que tem que criar essa tabela 

A ideia do ext.sqla é deixar tudo prontinho pra quem quiser usar a implementação de referencia só herdar daqui, escrever o mínimo de coisas, e ter o keyloop funcionando.

2020-03-16 15:39 UTC, jsbueno-geru commented on tests/api/v1/test_permission.py
> +    }
então - tem que ver se o description precisa ser obrigatório mesmo. se não for, não vai precisar deste teste - ou talvez, passar outro tipo de invalid-data (números, ou outro tipo de objeto que não seja uma string)

2020-03-16 15:39 UTC, jsbueno-geru commented on tests/api/v1/test_permission_grant.py
> +        }
Esse teste exercíta código que está na view - o que é ok. O problema é que olhando daqui parece que fica claro que se o identity não existe, essa chamda deveria tomar um 404, mas isso deveria ser papel do framework e das ferramentas, não da view.  

Em suma: a validação do Identity não deve estar na view, e sim ou na validação do Schema, ou em outra das validações automáticas do GRIP.

Não acho que precisa mudar isso agora - mas dá uma pensada,se concordar, coloque um cartão pra isso como débito técnico no backlog.  

(a ideia seria colcoar mecanismos ou no Schema ou no GRIP para sempre validar o identity, já que isso será necessário em quase todos os resources do projeto)

2020-03-16 15:39 UTC, jsbueno-geru commented on tests/api/v1/test_permission_grant.py
> +        }
Aí sim - no permissiongranted,ok testar manualmente pela existência de uma permission - é diferente do Identity)

2020-03-16 20:35 UTC, guilhermegeru commented
Parte das sugestões feitas pelo @jsbueno-geru foram resolvidas no PR #23 e outros pontos serão tratados em subtasks da [MERCHANTS-10](https://geruteam.atlassian.net/browse/MERCHANTS-10)